var songList = [
  {title:'Reflection (Sanaas Remix)', 
  artist:'Clion & Kamistory',
  id: 1,
  BPM: 173},
  {title:'Reflection (Yunomi Remix)',
  artist:'rekanan',
  id: 2,
  BPM: 150}, 
  {title:'Rosarium feat. 瑤山百霊',
  artist:'himmel',
  id:3,
  BPM: 148},
  {title:'Quickdraw',
  artist:'Sanaas',
  id:4,
  BPM: 150},
  {title:'song5',
  artist:'dog',
  id:5,
  BPM: 150},
  {title:'song6',
  artist:'cat',
  id:6,
  BPM: 170},
];

module.exports = songList;
